services:
  app:
    build: .
    container_name: ping-receipt
    ports:
      - "8000:8000"
    volumes:
      - ./database:/srv/database
      - ./public:/srv/public
      - ./resources:/srv/resources
      - ./config:/srv/config
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/srv/database/database.sqlite
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://ping.uche.ca
    command: ["php", "artisan", "serve", "--host", "0.0.0.0", "--port", "8000"]
    user: root
