services:
  app:
    build: .
    container_name: ping-receipt
    ports:
      - "8763:8000"
    volumes:
      - ./database:/srv/database
      - /dev/usb/lp0:/dev/usb/lp0
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/srv/database/database.sqlite
    user: root
